#!/bin/sh
# encoding: utf-8
# maintainer rgaudin

# apt-get install libnode-less

LESS_FILE=0

for file in `find ~/src -name 'pnlp.less'`
do
        LESS_FILE=$file
done

if [ $LESS_FILE = 0 ]; then
    echo "Unable to find your pnlp.less file"
    exit 1
fi

lessc $1 $2 $3 $LESS_FILE